### ISSUE TITLE
Can not change proxy to readymage - why?

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/create-scandipwa-app#18] opened 2021-01-25 10:46 UTC
### Describe the bug

I can not set my proxy to i.e. `https://whey-fe-dhc-1611229426.readymage.com` domain, why is it so?

**Comment by lianastaskevica** [comment] 2021-01-26 11:41
Closing as duplicate of #14

**Closed by lianastaskevica** 2021-01-26 11:41 UTC
