### ISSUE TITLE
Namespaces for modules with `-` are generated inconsistently

### ISSUE THREAD

**Issue by alfredsgenkins** [scandipwa/create-scandipwa-app#17] opened 2021-01-25 10:45 UTC
### Describe the bug

If the module contains more than one `-` in it's name, the namespace will be generated incorrectly:

![image](https://user-images.githubusercontent.com/29531824/105695678-06e6cc80-5f0b-11eb-914f-dbfe322c828a.png)

Gives following namespace for functions in it:

![image](https://user-images.githubusercontent.com/29531824/105695651-02221880-5f0b-11eb-93dc-a8f0f67ee77c.png)

**Comment by lianastaskevica** [comment] 2021-01-26 11:18
Closing as duplicate of https://github.com/scandipwa/create-scandipwa-app/issues/14

**Closed** 2021-01-26 13:35 UTC
